<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit598c7779091ffa5b875069f31948bfd0
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'TVW\\' => 4,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'TVW\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'H' => 
        array (
            'Httpful' => 
            array (
                0 => __DIR__ . '/..' . '/nategood/httpful/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit598c7779091ffa5b875069f31948bfd0::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit598c7779091ffa5b875069f31948bfd0::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit598c7779091ffa5b875069f31948bfd0::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
